### ISSUE TITLE
Wrong IP?

### ISSUE THREAD

**Issue by sapsolman** [SecOps-Institute/LinkedInIPLists#1]
Hi,
When I checking an IPs of Linkedin -> https://www.whatsmydns.net/#A/linkedin.com = IP is 13.107.42.14
But into your file "linkedin_ipv4_cidr_blocks.lst" I could not find this IP 
Could you check it?
![2021-02-28 19 57 36](https://user-images.githubusercontent.com/35896452/109426542-47040800-79ff-11eb-9379-b98a845158b4.jpg)

**Comment by osas1111** [comment]
You can find new ips in this pr
https://github.com/SecOps-Institute/LinkedInIPLists/pull/2/files

**Comment by osas1111** [comment]
IP for Russia is not valid, because Linkedin is blocked there
